# Generated by Django 4.1.7 on 2023-03-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='glutenfree',
            field=models.BooleanField(default=False),
        ),
    ]
